repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: check-merge-conflict
    - id: check-added-large-files
      args:
        - --maxkb=2000
    - id: detect-private-key

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
    - id: pyupgrade

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
    - id: ruff
      language_version: python3
    - id: ruff-format
      args: [ --check ]
      language_version: python3

-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    - id: isort
      language_version: python3

- repo: https://github.com/pdm-project/pdm
  rev: 2.20.1
  hooks:
    - id: pdm-lock-check
