services:
  chromadb:
    # image: chromadb/chromadb:latest
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "9000:8000"
    environment:
      - CHROMADB_CONFIG=/etc/chromadb/config.yml
    volumes:
      - ${PWD}/chroma_data:/var/lib/chromadb

  redis:
    image: redis:latest

    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db


volumes:
  mongo-data:
  redis_data:
