version: '3.8'

services:
  chromadb:
    image: chromadb/chromadb:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    environment:
      - CHROMADB_CONFIG=/etc/chromadb/config.yml
    volumes:
      - ${PWD}/chroma_data:/var/lib/chromadb

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  redis_data:
  mongo_data:
