version: '3.8'

services:
  chromadb:
    image: chromadb/chromadb:latest
    container_name: chromadb
    ports:
      - "7000:8000"
    environment:
      - CHROMADB_CONFIG=/etc/chromadb/config.yml
    volumes:
      - ${PWD}/chroma_data:/var/lib/chromadb

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
